library(tidyr)
library(stringr)
library(dplyr)
library(ggplot2)
grd <- read.csv("C:\\IIITB\\EDA\\grades.csv")
#grd$submit_time <- as.Date(grd$submit_time, "%m/%d/%y")
grd$submission <- as.character(grd$submission)
frmat <- str_sub(grd$submission,regexpr("(([0-9])([.]))",grd$submission)+2)
zip_per <- length(which(frmat=="zip"))/nrow(grd)
dln_date <- as.Date("01/03/17-23:59:00","%m/%d/%y-%H:%M:%S")
sub_date <- as.Date(grd$submit_time,"%m/%d/%y-%H:%M:%S")
late_sub <- which(sub_date>dln_date)
ord<- grd %>% group_by(as.Date(grd$submit_time,"%m/%d/%y-%H:%M:%S")) %>% summarise(cnt=n())
sub_date1 <- strptime(grd$submit_time,"%m/%d/%y-%H:%M:%S")
date <- format(sub_date1,"%d")
hr <- format(sub_date1,"%H")
ord_hr <- cbind(grd,hr)

cnt_hr <- ord_hr %>% group_by(hr) %>% summarise(cnt=n())

